site_name: Bear Firmware BaseBoard API
site_url: https://fw.api.bearrobotics.ai/
copyright: Copyright 2025 Bear Robotics, Inc. All rights reserved.
theme:
  name: 'material'
  features:
    - content.code.copy
    - content.tooltips
    - navigation.top
    - navigation.tabs
    - toc.follow
  palette:
    primary: custom
  favicon: assets/favicon.png
  logo: assets/bear_logo_white.png
extra_css:
    - stylesheets/extra.css
markdown_extensions:
  - toc:
      permalink: True
      toc_depth: 4
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
nav:
  - API Reference:
    - Firmware API:
      - Overview: BaseBoard API/overview/communication.md
      - Packet: 
        - Packet Structure: BaseBoard API/packet/packet-structure.md
        - Motor Packet: BaseBoard API/packet/motor-packet.md
        - Maincoms Packet: BaseBoard API/packet/maincoms-packet.md
        - CAN Packet: BaseBoard API/packet/can-packet.md
        - BaseLedCommand Packet: BaseBoard API/packet/baseledcommand-packet.md
        - IMU Packet: BaseBoard API/packet/imu-packet.md
        - ChargerManager Packet: BaseBoard API/packet/chargermanager-packet.md
        - BMS Packet: BaseBoard API/packet/bms-packet.md
        - Log Packet: BaseBoard API/packet/log-packet.md
  - Changelog: changelog.md
