#ifndef EXAMPLE_NODE_MOTOR_PACKETS_H
#define EXAMPLE_NODE_MOTOR_PACKETS_H

#include "example_node/packet_headers.h"

namespace bear {
namespace example_node {

typedef enum {
  MOTOR_PARAM_NONE = 0,
  // Must be equal to 1 for backwards compatibility
  MOTOR_PARAM_SPEED_KRPM = 1,
  // Must be equal to 2 for backwards compatibility
  MOTOR_PARAM_SPEED_P = 2,
  MOTOR_PARAM_SPEED_I,
  MOTOR_PARAM_SPEED_D,
  MOTOR_PARAM_SPEED_FF,
  MOTOR_PARAM_SPEED_DN,
  MOTOR_PARAM_ENCODER_VEL,
  MOTOR_PARAM_VERSION,
  MOTOR_PARAM_STATUS,
  MOTOR_PARAM_FAULT_RESET,
  MOTOR_PARAM_ENABLE_MOTOR,
  MOTOR_PARAM_ALERT,           //!< Alert packet generated by main controller
  MOTOR_PARAM_SPEED_OUT,       //!< Automatically set by the motor board and is
                               //!< exposed only for debugging purposes
  MOTOR_PARAM_END = 0x7FFFFFFF // Force enum to 32 bits
} MOTOR_PARAM;

typedef packed_arm union {
  float f32;
  uint32_t u32;
} packed_gcc MotorArg;

typedef packed_arm struct net_motor_packet_v2_t {
  NetPacketHeader header;
  MOTOR_PARAM param;
  MotorArg arg1;
  MotorArg arg2;
} packed_gcc NetMotorPacketV2;

typedef packed_arm struct net_send_motor_packet_v2_t {
  TSNetPacketHeader header;
  MOTOR_PARAM param;
  MotorArg arg1;
  MotorArg arg2;
  MotorArg arg3;
  MotorArg arg4;
} packed_gcc NetSendMotorPacketV2;

} // namespace example_node
} // namespace bear
#endif // EXAMPLE_NODE_MOTOR_PACKETS_H